# Generated by Django 4.0.5 on 2022-06-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instru', models.CharField(choices=[('GU', 'Guitarra'), ('VI', 'Violão'), ('SO', 'Sopros'), ('AC', 'Acessórios'), ('PI', 'Piano'), ('BA', 'Bateria'), ('BI', 'Baixo'), ('AR', 'Arpas')], default='GU', max_length=8, verbose_name='Escolha o Produto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca (opcional)')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo (opcional)')),
            ],
        ),
    ]
