# Generated by Django 4.0.5 on 2022-06-15 23:27

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.BigIntegerField()),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('nascimento', models.DateField(max_length=8, verbose_name='Data de Nascimento')),
                ('senha', models.CharField(max_length=8, verbose_name='Senha')),
                ('senha1', models.CharField(max_length=8, verbose_name='Confirme sua senha')),
            ],
        ),
    ]
