# Generated by Django 4.0.5 on 2022-06-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Titular')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('numero', models.BigIntegerField(verbose_name='Número do cartão')),
                ('data', models.DateField(max_length=6, verbose_name='Data de Validade')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('deb', models.CharField(choices=[('DE', 'Débito'), ('CR', 'Crédito')], default='DE', max_length=2, verbose_name='Débito ou Crédito')),
            ],
        ),
    ]
